### GET Request
GET http://localhost:8000/api/v1/users

### POST Method

POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "Address":"Dhading Nepal",
  "city": "Kathmandu",
  "religion":"HIndu"
}

### Patch Method
PATCH http://localhost:8000/api/v1/users
Content-Type: application/json
 
{
    "_id": "67b0585e4ff88e184d2a5beb",
    "Address": "Adamghat",
    "City":"Dhading"
}

### Delete Method
DELETE http://localhost:8000/api/v1/users/67b0585e4ff88e184d2a5beb
Content-Type: application/json

